version: '3.8'

services:
  web:
    image: odoo:17.0
    container_name: odoo_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # Modüllerinizi Odoo'nun extra-addons dizinine mount edin
      - .:/mnt/extra-addons
      # Odoo data'yı persist edin
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: unless-stopped
    command: -- --dev=all

  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # PostgreSQL data'yı persist edin
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  odoo-web-data:
    driver: local
  odoo-db-data:
    driver: local
